Repository sameergceian/hacktoberfeast2020, pull requests merged in 2020-10, with the labels that each got.

#1 Create Gcd using recursion
  Gcd using recursion
Labels: Hacktober, Hacktoberfeast, Hacktoberfeast-accepted

#2 Create Tell me any date , I will tell you Day
  Tell me any date , I will tell you Day
Labels: Hacktober, Hacktoberfeast, Hacktoberfeast-accepted, good first issue

#6 Swap two variables
  Swap two variable
Labels: Hacktober, Hacktoberfeast, Hacktoberfeast-accepted, Hacktoberfest2020
